### ISSUE TITLE
Importer issues

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/spark-website#12]
this is a quick place to record issues that we need to address for the content import:

**Comment by davidnuescheler** [comment]
on template pages like this:

https://spark-website--adobe.hlx.live/templates/announcements

it seems that we are importing `h3` instead of `h2`

**Comment by davidnuescheler** [comment]
the spark features, probably should be a content fragement instead, at least it seems recurring...

https://spark-website--adobe.hlx.live/make/brochure-maker

see:

https://spark.adobe.com/make/brochure-maker/
https://spark.adobe.com/make/brochure-maker/tri-fold/

**Comment by davidnuescheler** [comment]
i think the .docx behind this page could be a good template for the blog post...

https://spark-website--adobe.hlx.page/blog/posts/2020/facebookshops

@rofe i added some custom metadata, FYI

**Comment by kptdobe** [comment]
> on template pages like this:
> 
> https://spark-website--adobe.hlx.live/templates/announcements
> 
> it seems that we are importing `h3` instead of `h2`

No treatment is made, `h3` stays `h3`.

**Comment by davidnuescheler** [comment]
on some pages the template list (usually consists of a single "image" without the edit link) the image is "much larger". i used a "large" option in there, but i think we can use that by default if we find a single "image" in a "template list" block... thoughts?

**Comment by davidnuescheler** [comment]
as online word doesn't support linked images i started using just "pasted link" where the link text starts with `https://` immediately following the links as an indication that something is a link that should have been on the image. it looks like the importer currently uses the term "Template" for that, and we could change that, i would create an other do-not-translate item...

so on somthing like this, https://spark-website--adobe.hlx.page/express/feature/photography/resize.md i think it would be ideal if we had the link just bare bone, instead of having a `Template` text on it.

so the first template list would look something like this:

```
| Template List                                                                                                                                   |   |
| ----------------------------------------------------------------------------------------------------------------------------------------------- | - |
| ![Image Resizer](https://hlx.blob.core.windows.net/external/a44ad66c46d3c219b917e748e0247484332831bf "Image Resizer") <https://adobesparkpost.app.link/g8sk4xb8AV> |   |
| ![Image Resizer](https://hlx.blob.core.windows.net/external/25f4eb0565b3efce56c929a5da5bdd67ed950c1b "Image Resizer") <https://adobesparkpost.app.link/doId8gECEX> |   |
```

**Comment by kptdobe** [comment]
> as online word doesn't support linked images i started using just "pasted link" where the link text starts with `https://` immediately following the links as an indication that something is a link that should have been on the image. it looks like the importer currently uses the term "Template" for that, and we could change that, i would create an other do-not-translate item...
> 
> so on somthing like this, https://spark-website--adobe.hlx.page/express/feature/photography/resize.md i think it would be ideal if we had the link just bare bone, instead of having a `Template` text on it.
> 
> so the first template list would look something like this:
> 
> ```
> | Template List                                                                                                                                   |   |
> | ----------------------------------------------------------------------------------------------------------------------------------------------- | - |
> | ![Image Resizer](https://hlx.blob.core.windows.net/external/a44ad66c46d3c219b917e748e0247484332831bf "Image Resizer") <https://adobesparkpost.app.link/g8sk4xb8AV> |   |
> | ![Image Resizer](https://hlx.blob.core.windows.net/external/25f4eb0565b3efce56c929a5da5bdd67ed950c1b "Image Resizer") <https://adobesparkpost.app.link/doId8gECEX> |   |
> ```

I have made the change and re-imported the file: https://spark-website--adobe.hlx.page/express/feature/photography/resize.md contains the latest version of the importer.

**Comment by kptdobe** [comment]
> on some pages the template list (usually consists of a single "image" without the edit link) the image is "much larger". i used a "large" option in there, but i think we can use that by default if we find a single "image" in a "template list" block... thoughts?
> 
> eg. https://spark.adobe.com/make/add-music-to-video/

Is this a design or author choice ? If this is a design behaviour, you should keep the same format and make it large per design. If the author can decide, then we need extra options and adjust the importer accordingly.

**Comment by davidnuescheler** [comment]
https://spark-website--adobe.hlx.live/express/create/banner/image

**Comment by davidnuescheler** [comment]
i still see broken images... 

https://www.adobe.com/express/create/invitation/sleepover

<img width="449" alt="Screen Shot 2021-03-23 at 1 36 43 PM" src="https://user-images.githubusercontent.com/5289336/112214773-d5257580-8bdc-11eb-8263-cc10fd139e20.png">

**Comment by tripodsan** [comment]
looks good for me:

![image](https://user-images.githubusercontent.com/917628/112236829-b4b0f600-8c84-11eb-9ff0-08393d5505a1.png)

**Comment by tripodsan** [comment]
@kptdobe do you use the latest document support with the content-encoding fix?
https://github.com/adobe/helix-documents-support/commit/3b04f3db8f4d8746ad8e41f086d0e5e1f58aa7eb

**Comment by davidnuescheler** [comment]
this page looks weird https://spark-website--adobe.hlx.live/express/create/logo/camera

**Comment by davidnuescheler** [comment]
import metadata block with title and description for all make/template pages

**Comment by kptdobe** [comment]
> @kptdobe do you use the latest document support with the content-encoding fix?
> [adobe/helix-documents-support@3b04f3d](https://github.com/adobe/helix-documents-support/commit/3b04f3db8f4d8746ad8e41f086d0e5e1f58aa7eb)

I have 2.2.11 installed locally, thus yes fix should be in.

**Comment by kptdobe** [comment]
@tripodsan On top of being broken, those images are not the expected one... The 2 broken images are not on the original page!! 
https://spark.adobe.com/templates/invitation-maker/sleepover/ vs https://spark-website--adobe.hlx.live/express/create/invitation/sleepover
Maybe adobe/helix-documents-support#125 ?

**Comment by kptdobe** [comment]
> import metadata block with title and description for all make/template pages

I am not sure why you referenced that: this is already the case.. see https://spark-website--adobe.hlx.live/express/create/invitation/sleepover.md (at the bottom) and source for https://spark-website--adobe.hlx.live/express/create/invitation/sleepover

**Comment by tripodsan** [comment]
> @tripodsan On top of being broken, those images are not the expected ones... The 2 broken images are not on the original page!!
> https://spark.adobe.com/templates/invitation-maker/sleepover/ vs https://spark-website--adobe.hlx.live/express/create/invitation/sleepover
> Maybe [adobe/helix-documents-support#125](https://github.com/adobe/helix-documents-support/issues/125) ?

ok, I'll have al look again

**Comment by kptdobe** [comment]
> this page looks weird https://spark-website--adobe.hlx.live/express/create/logo/camera

Fixed with https://github.com/adobe/spark-website/issues/39

**Comment by davidnuescheler** [comment]
the sizes pages look weird they have a how steps at the bottom with titles only... 

https://spark-website--adobe.hlx.live/express/discover/sizes/youtube

**Comment by kptdobe** [comment]
> the sizes pages look weird they have a how steps at the bottom with titles only...
> 
> https://spark-website--adobe.hlx.live/express/discover/sizes/youtube

Some fixed the original page (very recently) because I re-imported it and it is fixed!

**Comment by rofe** [comment]
I think this can be closed now.
