### ISSUE TITLE
Migrate purge-code to hlx3

### ISSUE THREAD

**Issue by rofe** [adobe/spark-website#147]
The `purge-code` [action](https://github.com/adobe/spark-website/blob/main/.github/workflows/purge-code.yaml) currently still tries to use hlx2 purge to publish code changes. This should be migrated to the hlx3 code bus.

**Comment by rofe** [comment]
Or will it no longer be needed once the project is fully migrated to hlx3? @tripodsan

**Comment by tripodsan** [comment]
I don't know if this is required or how the code is cached. but it could be done automatically by the `code-bus`

**Comment by davidnuescheler** [comment]
that's a good question... intuitively is feels like the `codebus` itself doesn't know anything about the actual origin or the existence of the `.live` or the BYO CDN, where both content and code would have to be purged. 
so, intuitively this should be a part of the helix bot / action and possibly and possibly be part of the admin service constellation, as at least the purging part with the different CDNs would be the same for both content and code.

**Comment by rofe** [comment]
It looks like the `code-bus` already takes care of updating the preview (`hlx3.page`). In that case, all the `purge-code` action needs to do is send a Fastly `PURGE` request to make it available on `hlx.live`...

**Comment by tripodsan** [comment]
> It looks like the code-bus already takes care of updating the preview (hlx3.page)

no, the helix-bot just tells code-bus to update the files. since hlx3.page is not cached, it is automatically reflected.

>  In that case, all the purge-code action needs to do is send a Fastly PURGE request to make it available on hlx.live...

this should be as simple as sending a `flush` operation to the admin (TBD). either triggered by the code-bus (after updating the files) or the helix-bot (hoping that no-one requests the file while still stale).

**Comment by rofe** [comment]
> this should be as simple as sending a flush operation to the admin (TBD). either triggered by the code-bus (after updating the files) or the helix-bot (hoping that no-one requests the file while still stale).

Ok, until we have a `flush` operation, we can temprarily still use Fastly `PURGE`, right?

**Comment by rofe** [comment]
No longer needed
