### ISSUE TITLE
column blocks have inconsistent styling in grid

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/spark-website#162]
The column blocks render incorrectly. 3rd column in a 3 width column block renders slightly below the others in a side by side; this is caused by the div container height being relatively shorter than the other columns!

check https://main--spark-website--adobe.hlx.page/express/trial/14

**Comment by rofe** [comment]
@MarquiseRosier I believe this is a duplicate of https://github.com/adobe/express-website-issues/issues/138
