### ISSUE TITLE
Move sitemap.xml back to github

### ISSUE THREAD

**Issue by rofe** [adobe/spark-website#177]

**Comment by tripodsan** [comment]
why? eventually, they will remain in content-bus, right?

**Comment by davidnuescheler** [comment]
it is a hybrid, the sitemap that includes the sitemap index (and looks like this:
https://www.adobe.com/express/sitemap.xml) is something that is usually created and curated by a developer and there it is also plausible that changes to it could be staged on branches so codebus is the correct location... 
the sitemap that contains references to the actual pages (looks more like this: https://www.adobe.com/express/sitemap-us.xml) should be maintained in tandem with published content in contentbus.
