### ISSUE TITLE
[a11y] homepage tabstop, keyboard indicators

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/spark-website#33]
https://spark-website--adobe.hlx.live/express/

- [x] make sure that all the tabstops show keyboard indicator (focus)
- [ ] h5 should probably be a `<p>`

**Comment by tripodsan** [comment]
> h5 should probably be a <p>

@davidnuescheler what should be done about the H5? when I change it in the document to a normal paragraph, it get too small.

should we change the H5 element into a `<p>` and add a class="h5" to it ?
