### ISSUE TITLE
[a11y] pricing page

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/spark-website#38]
https://spark-website--adobe.hlx.live/express/pricing

top left animation needs to be able to be stoppable
top left animation needs to be hidden from screenreader and alternate aria containing all the combined text
icons in pricing should have `alt=""` as they are purely decorative
strike-through price needs screen reader support saying "discounted from"
dropdowns need a label
table needs to be rendered as `<table>`
check marks in table need `yes` as alt-text vs. `alt=""` for icons options that are not included
links with link text "here", "here" and "learn more" should be more descriptive and unique

**Comment by rofe** [comment]
@williambsm could you take this?

**Comment by williambsm** [comment]
https://github.com/adobe/spark-website/pull/61

"links with link text "here", "here" and "learn more" should be more descriptive and unique" is waiting on further feedback, rest is fixed.
