### ISSUE TITLE
module type mismatch on h2 push 

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/spark-website#43]
currently we are receiving warnings from chrome about two of our h2 pushes not being used

https://spark-website--adobe.hlx.live/express/

it would be great if we had some form of an isolated h2 test service, where we can easily play around with header etc. in an outerCDN.

**Comment by trieloff** [comment]
In version 35 I'm using `</express/scripts/scripts.js>; rel=modulepreload; as=script; crossorigin=use-credentials, </express/styles/styles.css>; rel=preload; as=style, </express/testing.json>; rel=preload; as=fetch; crossorigin=anonymous` and I don't see the warnings anymore, but `scripts.js` is still being double-fetched.

**Comment by trieloff** [comment]
I think I've got it: https://push-me.hlx.live/ https://manage.fastly.com/configure/services/2IoEXKgmmmdULrVtb39Rf8/versions/4/contents

No warnings, `/script.js` is only pushed, not fetched and the module is being loaded.
