### ISSUE TITLE
path is index files ends with .html

### ISSUE THREAD

**Issue by kptdobe** [adobe/spark-website#51]
Open the query-index, all paths end with .html.

Sine we decided to get rid of the extension everywhere (canonical urls, client side code...), I think this should be reflected in the index too.

cc @dominique-pfister @davidnuescheler

**Comment by dominique-pfister** [comment]
And they shouldn't?

**Comment by kptdobe** [comment]
Oops, sorry, I was writing the issue and jumped on something else. I added more details.

**Comment by dominique-pfister** [comment]
We can get rid of the extension, but then the client code (e.g. sitemap.xml or cards in other projects) needs to be adapted, too.

**Comment by rofe** [comment]
Done
