### ISSUE TITLE
Enlarge Templates and Assets visual

### ISSUE THREAD

**Issue by skelleyadobe** [adobe/spark-website#53]
Can you enlarge the visual to the right of the copy block? Currently the copy block outweighs the visual. Can you increase size by 10-15%?

**Comment by davidnuescheler** [comment]
currently we split the width 50% / 50% and then max out the space for the image... so the only way i could do that is by splitting things differently, which would produce alignment issues with other blocks. is that a `30/70` split, can we give that a name, so we can give an author the option to that? an other alternative would be to just crop the image more closely (if that's possible) i haven't looked.

**Comment by skelleyadobe** [comment]
I don't think it's the crop. Can we increase the height of the block? There might be ~20 versions of this type of value prop content and we're hoping the image will have a presence and that the copy block doesn't outweigh the visual footprint. Are you think this could be a unique type of block specific to value props? 


<img width="929" alt="Screen Shot 2021-03-25 at 12 36 35 PM" src="https://user-images.githubusercontent.com/81386348/112533916-b43d5b80-8d67-11eb-9d14-9a018fdcb007.png">
