### ISSUE TITLE
importer: don't use image title if it's the same as the alt text

### ISSUE THREAD

**Issue by tripodsan** [adobe/spark-website#66]
the image title has little value if it's the same than the alt text.

from the a11y checker:

#### What It Means
Title attribute text is the same as text or alternative text.
#### Why It Matters
The title attribute value is used to provide advisory information. It typically appears when the users hovers the mouse over an element. The advisory information presented should not be identical to or very similar to the element text or alternative text.
#### How to Fix It
In most cases the title attribute can be removed, otherwise modify it to provide advisory, but not redundant information. Note that the title text may or may not be read by a screen reader and is typically inaccessible to sighted keyboard users.

**Comment by kptdobe** [comment]
I made the change, re-importing all content.

**Comment by kptdobe** [comment]
Content re-imported, title has disappeared (if == to alt).
