### ISSUE TITLE
Video block missing

### ISSUE THREAD

**Issue by kptdobe** [adobe/spark-website#78]
The following blog post contains a `Video` block which is missing. Or implemented in `Animation` but since the code is looking for `blocks/video/video.js`, this cannot work.

https://spark-website--adobe.hlx.page/express/learn/blog/introducing-thousands-of-design-assets-for-every-mood

cc @MarquiseRosier @davidnuescheler

**Comment by davidnuescheler** [comment]
it looks like these were animations, so i changed them in content.
